source("https://raw.githubusercontent.com/Shicheng-Guo/GscRbasement/master/OROSmerge.R")
source("https://raw.githubusercontent.com/Shicheng-Guo/GscRbasement/master/pancancermetadge.R")
source("https://raw.githubusercontent.com/Shicheng-Guo/GscRbasement/master/pancancermetaOsHr.R")
memo="BMCReview"
symbolist<-c("CMTM8","TP53")
pancancermetadge(symbolist,memo=paste(memo,".m6A.eQTL.pancancer.dge",sep=""))
pancancermetaOsHr(symbolist,memo=paste(memo,".m6A.eQTL.pancancer.hr.os",sep=""))
memo<-"oncosuppressor"
symbolist<-as.character(read.table("https://raw.githubusercontent.com/Shicheng-Guo/tcga/master/extdata/onco-suppressor/oncosuppressor.txt",as.is=T)[,1])
pancancermetadge(symbolist,memo=paste(memo,".m6A.eQTL.pancancer.dge",sep=""))
pancancermetaOsHr(symbolist,memo=paste(memo,".m6A.eQTL.pancancer.hr.os",sep=""))
OROSmerge(memo)
dge<-read.csv("oncosuppressor.m6A.eQTL.pancancer.dge.tcga.pancancer.smd.meta.pvalue.csv")
sym<-read.table("https://raw.githubusercontent.com/Shicheng-Guo/tcga/master/extdata/onco-suppressor/oncosuppressor.txt",as.is=T)
out<-merge(dge,sym,by.x="symbol",by.y="V1")
write.csv(out,file="oncosuppressor.expression.csv",quote=F)
nrow(subset(out,V2=="Oncogene" & beta>0))
nrow(subset(out,V2=="Oncogene" & beta<0))
nrow(subset(out,V2=="Suppressor" & beta>0))
nrow(subset(out,V2=="Suppressor" & beta<0))
